function setupLightbox(){0===$("#lightbox").length&&$("body").append(`
      <div id="lightbox" class="lightbox" role="dialog" aria-modal="true" aria-label="Image lightbox">
        <div class="lightbox__content">
          <img class="lightbox__img" src="" alt="" />
          <div class="lightbox__caption"></div>
        </div>
        <button class="lightbox__close" aria-label="Close lightbox"></button>
        <button class="lightbox__nav lightbox__nav--prev" aria-label="Previous image"></button>
        <button class="lightbox__nav lightbox__nav--next" aria-label="Next image"></button>
      </div>
    `);let i=$("#lightbox"),a=$(".lightbox__img"),l=$(".lightbox__caption");var t=$(".lightbox__close");let n=$(".lightbox__nav--prev"),c=$(".lightbox__nav--next"),s=$(".proj__img"),r=0,o=(s.on("click",function(){var t=$(this),o=t.attr("src"),e=t.attr("alt"),t=t.closest("figure").find("figcaption").text()||e;a.attr("src",o),a.attr("alt",e),l.text(t),r=s.index(this),s.length<=1?(n.hide(),c.hide()):(n.show(),c.show()),i.addClass("active"),$("body").css("overflow","hidden"),i.focus()}),s.attr("tabindex","0").on("keydown",function(t){"Enter"!==t.key&&" "!==t.key||(t.preventDefault(),$(this).click())}),t.on("click",h),i.on("click",function(t){t.target===this&&h()}),n.on("click",function(){d(-1)}),c.on("click",function(){d(1)}),$(document).on("keydown",function(t){if(i.hasClass("active"))switch(t.key){case"Escape":h();break;case"ArrowLeft":d(-1);break;case"ArrowRight":d(1)}}),0),e;function d(t){(r+=t)<0?r=s.length-1:r>=s.length&&(r=0);var t=s.eq(r),o=t.attr("src"),e=t.attr("alt"),t=t.closest("figure").find("figcaption").text()||e;a.attr("src",o),a.attr("alt",e),l.text(t)}function h(){i.removeClass("active"),$("body").css("overflow",""),s.eq(r).focus()}i.on("touchstart",function(t){o=t.originalEvent.touches[0].clientX}),i.on("touchend",function(t){(e=t.originalEvent.changedTouches[0].clientX)<o-50?d(1):e>o+50&&d(-1)})}$(document).ready(function(){$(window).scroll(function(){100<$(document).scrollTop()?$(".header").addClass("scrolled"):$(".header").removeClass("scrolled")}),setupLightbox()}),window.sr=ScrollReveal(),sr.reveal(".project",{duration:500,delay:500},50),sr.reveal(".about",{duration:500,delay:500},50),sr.reveal(".blurb",{duration:500,delay:500},50);