name: Build and Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: write
  checks: write
  pull-requests: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  # Comprehensive code quality checks
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Lint JavaScript/TypeScript
        run: npm run lint
      - name: Lint CSS/SCSS
        run: npm run stylelint
      - name: Check Prettier formatting
        run: npm run format:check
      - name: Check bundle size
        run: npm run test:bundle-size
      - name: Run unit tests
        run: npm run test
      - name: Build project
        run: npm run build

  # Performance regression testing gate
  performance-gate:
    uses: ./.github/workflows/performance-monitoring.yml
    needs: [quality]
    secrets: inherit

  # Build and deploy
  build-and-deploy:
    needs: [quality, performance-gate]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build site
        run: npm run build

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Deploy to GitHub Pages
  deploy:
    needs: [build-and-deploy]
    # Deploy on pushes to main or manual dispatch
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
